### ISSUE TITLE
Tests failing, ports problem

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/ddev-swagger-ui#1]
Hey @rfay,

I cannot get the port and tests fixed, could you take a look?

The test is calling a curl on a localhost URL (taken from other DDEV add-ons), but it cannot reach the Swagger UI instance. 

I'm not sure if I set up the ports correctly in the compose yaml.

I added multiple curl test.

```
# Restarted test-swagger-ui
# Your project can be reached at https://test-swagger-ui.ddev.site/ https://127.0.0.1:32778/
# Failed to execute command curl -s http://localhost:8080: exit status 7
# ddev get ddev/ddev-swagger-ui with project test-swagger-ui in /home/runner/tmp/test-swagger-ui (/home/runner/tmp/test-swagger-ui)
not ok 2 install from release
```

curl command outside on https://test-swagger-ui.ddev.site works in test and loading the addon in my project works fine, too.

Would be very kind if you can take a look.

**Comment by rfay** [comment]
Also note the ddev-addon-template instructions about how you can actually ssh into github's world, https://github.com/ddev/ddev-addon-template#how-to-debug-tests-github-actions

**Comment by reloxx13** [comment]
But the test instance port is random, right?

I just wanted to check if the swagger ui webpage is reachable and confirm swagger ui started.

Port 8080 is in addona compose yaml

**Comment by rfay** [comment]
What do you want to curl? You can curl the project with `curl https://test-swagger-ui.ddev.site/`

**Comment by reloxx13** [comment]
Thats right, but that ddev curl on localhost i found at other addons does not work with my addon, so i think something is odd or wrong configured with the ports in the compose file.

**Comment by reloxx13** [comment]
I want to curl the swagger ui webpage served by my addon.

**Comment by rfay** [comment]
Oh, https://github.com/reloxx13/ddev-swagger-ui/blob/1bc266dac1dd411913ce7ca52dd1a04b931a3dc6/docker-compose.swagger-ui.yaml#L3-L10

You really can't use `ports` normally in a `docker-compose.*.yaml` because then people can only run one project (they'll conflict on 8080). 

Assuming swagger-ui is an HTTP service, you would do it with HTTP_EXPOSE and HTTPS_EXPOSE, like in https://github.com/ddev/ddev-phpmyadmin/blob/393b83e7f8fc586d749eeb828762a33a3a4f23ca/docker-compose.phpmyadmin.yaml#L20-L21

**Comment by rfay** [comment]
See https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/

**Comment by reloxx13** [comment]
Heya,
okay i remove the port and reduced the test to only test `https://test-swagger-ui.ddev.site/`
Thank you very much for your hints 👍🏻
