### ISSUE TITLE
Suggestions for ddev-swagger-ui

### ISSUE THREAD

**Issue by rfay** [reloxx13/ddev-swagger-ui#2]
Thanks for this contribution and for being willing to maintain it!

Just some thoughts looking through:
1. The README assumes that people already know what swagger is and why they would want it. I don't. Maybe you can add a little more about "Why would I use this add-on?"
2. Why would one use swagger inside a project? Isn't it a standalone tool? How does it help to have it in a project? (That's the kind of thing that can go in the README as well)
3. As noted elsewhere, I'm not a maintainer of this, so remove my name from the bottom. I don't know a thing about swagger.
4. You're using HTTP_EXPOSE and HTTPS_EXPOSE on the same port, 8080. That won't work for most browsers. I don't know how it can be working for you. They should be two different ports (but point to the same 8080 that's exposed inside the container)
5. I recommend using something other than 8080/8081 as the HTTP*_EXPOSE anyway because that's a very commonly used port and is likely to cause trouble. Try 9080/9081 maybe.
6. I usually recommend using an explicit tag for the image. You have `image: swaggerapi/swagger-ui` which actually means `image: swaggerapi/swagger-ui:latest`, and on most docker images `latest` is a tag that is moved all the time, which means your add-on can suddenly break for people when it's changed upstream.
7. The `version` tag is obsolete and no longer used in docker-compose, so you can remove that. 

Again, thanks for the contribution!

**Comment by reloxx13** [comment]
Thank you very much for the feedback!
