### ISSUE TITLE
Tests not working - is this maintained?

### ISSUE THREAD

**Issue by rfay** [reloxx13/ddev-swagger-ui#3]
I see that the automated tests aren't working now and maybe haven't ever?

If this is intended to be a maintained add-on, could you get them going? 

If not, would you mind removing the `ddev-get` topic from the repo so it doesn't confuse people?

Thanks!
-Randy

**Comment by reloxx13** [comment]
Tests fixed

**Comment by rfay** [comment]
Congrats and thanks!
